//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxCascadingDropdown.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int prodid { get; set; }
        public string proddesc { get; set; }
        public Nullable<decimal> prodprice { get; set; }
        public Nullable<int> cateid { get; set; }
    
        public virtual category category { get; set; }
    }
}
